package vista;

import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import vista.util.*;
/**
 *
 * @author carlo
 */
public class InicioSesion extends javax.swing.JFrame {
    // Definicion de imagenes 
    ImagenEnJLabel iconoOjo;
    ImagenEnJLabel imagenFondoPrincipal;
    ImagenEnJLabel iconoLogo;
    ImagenEnJLabel iconoUsuario;
    ImagenEnJLabel iconoCandado;
    
    
    // CONSTANTES GLOBALES 
    private final int ANCHO_VENTANA = 1011; 
    private final int ALTO_VENTANA = 645;
    
    private final String PLACEHOLDER_TXT_USUARIO    = "Ingresa el Usuario";
    private final String PLACEHOLDER_TXT_CONTRA     = "**********";
    
    private boolean seVeLaContra = false; 
    
    /**
     * Creates new form InicioSesion
     */
    public InicioSesion() {
        initComponents();
        //-- PROPIEDADES DE LA VENTANA --//
        this.setLocationRelativeTo(null); // Centrado
        this.setTitle("Acceso al Sistema");
        this.setSize(ANCHO_VENTANA, ALTO_VENTANA); // Tamaño fijo 
        this.setResizable(false);
        
        //-- IMAGENES --// 
        this.cargarImagenes();
       
        
        
    }
    
    public void cargarImagenes() {
        // Añadir imagen de fondo 
        imagenFondoPrincipal = new ImagenEnJLabel(bgPrincipalJLabel, 
                "imagenesDeFondo/fondoPrincipalLogin.png");
        // Icono logo 
        iconoLogo = new ImagenEnJLabel(iconoLogoJLabel, 
                "iconos/logo.png");
        // Iconos de cuadros de texto
        iconoUsuario = new ImagenEnJLabel(iconUserJLabel, 
                "iconos/usuario.png");
        iconoCandado = new ImagenEnJLabel(iconContraJLabel, 
                "iconos/candado.png");
        iconoOjo = new ImagenEnJLabel(iconOjoJLabel,
                "iconos/ojo.png");
        this.repaint();
    }
    
    
    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("iconos/iconoLogo.jpg"));
        return retValue;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRegistrate = new javax.swing.JButton();
        btnRegistrate1 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        txtNoCuenta = new javax.swing.JLabel();
        iconoLogoJLabel = new javax.swing.JLabel();
        txtContraContainer = new javax.swing.JPanel();
        btnMostrarContra = new javax.swing.JButton();
        iconOjoJLabel = new javax.swing.JLabel();
        baseLinetxt = new javax.swing.JPanel();
        txtContrajLabel = new javax.swing.JPasswordField();
        iconContraJLabel = new javax.swing.JLabel();
        jLabelMostrar = new javax.swing.JLabel();
        txtUserContainer = new javax.swing.JPanel();
        iconUserJLabel = new javax.swing.JLabel();
        baseLinetxt1 = new javax.swing.JPanel();
        txtUserJLabel = new javax.swing.JTextField();
        jLabelInciarSesion = new javax.swing.JLabel();
        bgPrincipalJLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnRegistrate.setFont(Tema.FUENTE_NORMAL);
        btnRegistrate.setForeground(Tema.ROJO_VIBRANTE);
        btnRegistrate.setText("Continuar sin iniciar Sesión →");
        btnRegistrate.setToolTipText("");
        btnRegistrate.setBorder(null);
        btnRegistrate.setBorderPainted(false);
        btnRegistrate.setContentAreaFilled(false);
        btnRegistrate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegistrate.setFocusPainted(false);
        btnRegistrate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrateActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegistrate, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 10, 220, 30));

        btnRegistrate1.setFont(Tema.FUENTE_NORMAL_BOLD);
        btnRegistrate1.setForeground(Tema.ROJO_VIBRANTE);
        btnRegistrate1.setText("Regístrate");
        btnRegistrate1.setToolTipText("");
        btnRegistrate1.setBorder(null);
        btnRegistrate1.setBorderPainted(false);
        btnRegistrate1.setContentAreaFilled(false);
        btnRegistrate1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegistrate1.setFocusPainted(false);
        btnRegistrate1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrate1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegistrate1, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 500, 70, 30));

        jButton1.setBackground(Tema.ROJO_VIBRANTE);
        jButton1.setFont(new java.awt.Font("Arial Black", 1, 16)); // NOI18N
        jButton1.setForeground(Tema.BLANCO);
        jButton1.setText("INGRESAR");
        jButton1.setToolTipText("");
        jButton1.setAlignmentY(-0.5F);
        jButton1.setBorder(null);
        jButton1.setFocusPainted(false);
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 450, 340, 40));

        txtNoCuenta.setFont(Tema.FUENTE_NORMAL);
        txtNoCuenta.setForeground(Tema.BLANCO);
        txtNoCuenta.setText("¿No tienes cuenta?");
        getContentPane().add(txtNoCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 500, -1, 30));

        iconoLogoJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconoLogoJLabel.setText("Logo Empresa");
        getContentPane().add(iconoLogoJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 70, 160, 160));

        txtContraContainer.setBackground(Tema.GRIS_OSCURO);
        txtContraContainer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnMostrarContra.setBorder(null);
        btnMostrarContra.setBorderPainted(false);
        btnMostrarContra.setContentAreaFilled(false);
        btnMostrarContra.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMostrarContra.setFocusPainted(false);
        btnMostrarContra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnMostrarContraMousePressed(evt);
            }
        });
        txtContraContainer.add(btnMostrarContra, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 13, 100, 20));

        iconOjoJLabel.setText("icon");
        txtContraContainer.add(iconOjoJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 40, 40));

        baseLinetxt.setBackground(Tema.CREMA_CLARO);
        txtContraContainer.add(baseLinetxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 38, 400, 2));

        txtContrajLabel.setBackground(Tema.GRIS_OSCURO);
        txtContrajLabel.setFont(Tema.FUENTE_NORMAL);
        txtContrajLabel.setForeground(new java.awt.Color(93, 86, 79));
        txtContrajLabel.setText(this.PLACEHOLDER_TXT_CONTRA);
        txtContrajLabel.setBorder(null);
        txtContrajLabel.setFocusable(false);
        txtContrajLabel.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtContrajLabelFocusLost(evt);
            }
        });
        txtContrajLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtContrajLabelMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtContrajLabelMousePressed(evt);
            }
        });
        txtContraContainer.add(txtContrajLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 170, 37));

        iconContraJLabel.setText("icon");
        txtContraContainer.add(iconContraJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 40));

        jLabelMostrar.setFont(Tema.FUENTE_NORMAL);
        jLabelMostrar.setForeground(Tema.CREMA_CLARO);
        jLabelMostrar.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelMostrar.setText("Mostrar");
        txtContraContainer.add(jLabelMostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 0, 60, 40));

        getContentPane().add(txtContraContainer, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 380, 340, 40));

        txtUserContainer.setBackground(Tema.GRIS_OSCURO);
        txtUserContainer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        iconUserJLabel.setText("icon");
        txtUserContainer.add(iconUserJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 40));

        baseLinetxt1.setBackground(Tema.CREMA_CLARO);
        txtUserContainer.add(baseLinetxt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 38, 400, 2));

        txtUserJLabel.setBackground(Tema.GRIS_OSCURO);
        txtUserJLabel.setFont(Tema.FUENTE_NORMAL);
        txtUserJLabel.setForeground(Tema.TEXTO_OPACO_FONDOGRIS);
        txtUserJLabel.setText(this.PLACEHOLDER_TXT_USUARIO);
        txtUserJLabel.setBorder(null);
        txtUserJLabel.setFocusable(false);
        txtUserJLabel.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtUserJLabelFocusLost(evt);
            }
        });
        txtUserJLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtUserJLabelMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtUserJLabelMousePressed(evt);
            }
        });
        txtUserJLabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserJLabelActionPerformed(evt);
            }
        });
        txtUserContainer.add(txtUserJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 250, 37));

        getContentPane().add(txtUserContainer, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 310, 340, 40));

        jLabelInciarSesion.setFont(Tema.FUENTE_FUERTE);
        jLabelInciarSesion.setForeground(Tema.ROJO_VIBRANTE);
        jLabelInciarSesion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelInciarSesion.setText("INICIA SESIÓN");
        jLabelInciarSesion.setToolTipText("");
        jLabelInciarSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabelInciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 250, 340, 30));

        bgPrincipalJLabel.setBackground(new java.awt.Color(102, 102, 102));
        getContentPane().add(bgPrincipalJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1011, 645));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUserJLabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserJLabelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserJLabelActionPerformed

    private void btnRegistrateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegistrateActionPerformed

    private void btnRegistrate1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrate1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegistrate1ActionPerformed

    private void txtUserJLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtUserJLabelMouseClicked
        
    }//GEN-LAST:event_txtUserJLabelMouseClicked

    private void txtContrajLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtContrajLabelMouseClicked
        
        
    }//GEN-LAST:event_txtContrajLabelMouseClicked
    // Eliminar placeholder si se da click al TextField
    private void txtUserJLabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtUserJLabelMousePressed
        ManejadorEventosVisuales.eliminarPlaceHolder(
                txtUserJLabel, 
                PLACEHOLDER_TXT_USUARIO, 
                Tema.CREMA_CLARO);
    }//GEN-LAST:event_txtUserJLabelMousePressed

    private void txtContrajLabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtContrajLabelMousePressed
        ManejadorEventosVisuales.eliminarPlaceHolder(
                txtContrajLabel, 
                PLACEHOLDER_TXT_CONTRA, 
                Tema.CREMA_CLARO);
    }//GEN-LAST:event_txtContrajLabelMousePressed
    // Restaurar el placeholder si el campo está vacío 
    private void txtUserJLabelFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUserJLabelFocusLost
        ManejadorEventosVisuales.restaurarPlaceHolder(
                txtUserJLabel, 
                PLACEHOLDER_TXT_USUARIO, 
                Tema.TEXTO_OPACO_FONDOGRIS);
        
    }//GEN-LAST:event_txtUserJLabelFocusLost

    private void txtContrajLabelFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtContrajLabelFocusLost
        ManejadorEventosVisuales.restaurarPlaceHolder(
                txtContrajLabel, 
                PLACEHOLDER_TXT_CONTRA, 
                Tema.TEXTO_OPACO_FONDOGRIS);
    }//GEN-LAST:event_txtContrajLabelFocusLost

    // Desvelar contraseña 
    private void btnMostrarContraMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMostrarContraMousePressed
        if (seVeLaContra) {
            txtContrajLabel.setEchoChar('•'); 
            jLabelMostrar.setText("Mostrar"); 
            iconoOjo.setIcono("iconos/ojo.png");
            seVeLaContra = false;
        } else {
            txtContrajLabel.setEchoChar((char) 0); 
            jLabelMostrar.setText("Ocultar"); 
                        iconoOjo.setIcono("iconos/ojoAbierto.png");
            seVeLaContra = true;
        }
    }//GEN-LAST:event_btnMostrarContraMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel baseLinetxt;
    private javax.swing.JPanel baseLinetxt1;
    private javax.swing.JLabel bgPrincipalJLabel;
    private javax.swing.JButton btnMostrarContra;
    private javax.swing.JButton btnRegistrate;
    private javax.swing.JButton btnRegistrate1;
    private javax.swing.JLabel iconContraJLabel;
    private javax.swing.JLabel iconOjoJLabel;
    private javax.swing.JLabel iconUserJLabel;
    private javax.swing.JLabel iconoLogoJLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabelInciarSesion;
    private javax.swing.JLabel jLabelMostrar;
    private javax.swing.JPanel txtContraContainer;
    private javax.swing.JPasswordField txtContrajLabel;
    private javax.swing.JLabel txtNoCuenta;
    private javax.swing.JPanel txtUserContainer;
    private javax.swing.JTextField txtUserJLabel;
    // End of variables declaration//GEN-END:variables
}
