/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import javax.swing.JButton;
import javax.swing.JList;
import javax.swing.JTextArea;
import vista.util.ImagenEnJLabel;
import vista.util.Tema;

/**
 *
 * @author carlo
 */
public class VistaCompras extends javax.swing.JFrame {
    private ImagenEnJLabel fondoPrincipal; 
    private ImagenEnJLabel iconoCartelera; 
    private ImagenEnJLabel iconoCompras; 
    private ImagenEnJLabel iconoCuenta;
    
    
    private final int ANCHO_VENTANA = 1280; 
    private final int ALTO_VENTANA = 720;
    
    /**
     * Creates new form VistaCompras
     */
    public VistaCompras() {
        initComponents();
        configurarVentana();
        cargarImagenes();
    }
    
    public void configurarVentana(){
        this.setLocationRelativeTo(null); // Centrado
        this.setTitle("Sistema de Gestion Night Cine - Vista Administrador");
        this.setSize(ANCHO_VENTANA, ALTO_VENTANA); // Tamaño fijo 
        this.setResizable(false); // Tamaño fijo 
    }
    
    public void cargarImagenes() {
        // Añadir imagen de fondo 
        fondoPrincipal = new ImagenEnJLabel(fondoPrincipalJLabel, 
                "imagenesDeFondo/fondoPrincipalPrincipal.png");
         // Iconos Menu 
        iconoCartelera = new ImagenEnJLabel(iconoCaseteJLabel,
                "iconos/cartelera.png");
        iconoCompras = new ImagenEnJLabel(iconoCompraJLabel,
                "iconos/carrito.png");
        iconoCuenta = new ImagenEnJLabel(iconoCuentaJLabel,
                "iconos/cuenta.png");
    }

    public JButton getBtnCasete() {
        return btnCasete;
    }

    public JButton getBtnCompras() {
        return btnCompras;
    }

    public JButton getBtnCuenta() {
        return btnCuenta;
    }

    public JList<String> getListaCompras() {
        return listaCompras;
    }

    public JTextArea getTxtFactura() {
        return txtFactura;
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        iconoCaseteJLabel = new javax.swing.JLabel();
        iconoCompraJLabel = new javax.swing.JLabel();
        iconoCuentaJLabel = new javax.swing.JLabel();
        btnCasete = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnCompras = new javax.swing.JButton();
        btnCuenta = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaCompras = new javax.swing.JList<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtFactura = new javax.swing.JTextArea();
        txtCarteleraJLabel = new javax.swing.JLabel();
        fondoPrincipalJLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        iconoCaseteJLabel.setBackground(new java.awt.Color(204, 204, 204));
        iconoCaseteJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconoCaseteJLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(iconoCaseteJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 120, 120));

        iconoCompraJLabel.setBackground(new java.awt.Color(204, 204, 204));
        iconoCompraJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconoCompraJLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(iconoCompraJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, 120, 120));

        iconoCuentaJLabel.setBackground(new java.awt.Color(204, 204, 204));
        iconoCuentaJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconoCuentaJLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(iconoCuentaJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 430, 120, 120));

        btnCasete.setFont(Tema.FUENTE_ICONOS);
        btnCasete.setText("Cartelera");
        btnCasete.setBorderPainted(false);
        btnCasete.setContentAreaFilled(false);
        btnCasete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCasete.setFocusPainted(false);
        btnCasete.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(btnCasete, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 140, 140));

        jLabel3.setFont(Tema.FUENTE_NORMAL_BOLD);
        jLabel3.setForeground(Tema.CREMA_CLARO);
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("FACTURA PREVIEW");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 140, 150, -1));

        jLabel2.setFont(Tema.FUENTE_NORMAL_BOLD);
        jLabel2.setForeground(Tema.CREMA_CLARO);
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("HISTORIAL");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 140, 130, -1));

        btnCompras.setFont(Tema.FUENTE_ICONOS);
        btnCompras.setText("Compras");
        btnCompras.setBorderPainted(false);
        btnCompras.setContentAreaFilled(false);
        btnCompras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCompras.setFocusPainted(false);
        btnCompras.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(btnCompras, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, 140, 140));

        btnCuenta.setFont(Tema.FUENTE_ICONOS);
        btnCuenta.setText("Mi Cuenta");
        btnCuenta.setBorderPainted(false);
        btnCuenta.setContentAreaFilled(false);
        btnCuenta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCuenta.setFocusPainted(false);
        btnCuenta.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(btnCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 430, 140, 140));

        listaCompras.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listaCompras);

        jScrollPane2.setViewportView(jScrollPane1);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 180, 160, 290));

        txtFactura.setBackground(Tema.GRIS_OSCURO);
        txtFactura.setColumns(20);
        txtFactura.setForeground(Tema.BLANCO);
        txtFactura.setRows(5);
        txtFactura.setBorder(null);
        jScrollPane3.setViewportView(txtFactura);

        jScrollPane4.setViewportView(jScrollPane3);

        jPanel1.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 180, 320, 430));

        txtCarteleraJLabel.setBackground(Tema.ROJO_VIBRANTE);
        txtCarteleraJLabel.setFont(Tema.FUENTE_FUERTE_PLAIN);
        txtCarteleraJLabel.setForeground(Tema.CREMA_CLARO);
        txtCarteleraJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtCarteleraJLabel.setText("HISTORIAL DE COMPRAS");
        txtCarteleraJLabel.setOpaque(true);
        jPanel1.add(txtCarteleraJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 40, 430, 50));
        jPanel1.add(fondoPrincipalJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaCompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaCompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaCompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaCompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaCompras().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCasete;
    private javax.swing.JButton btnCompras;
    private javax.swing.JButton btnCuenta;
    private javax.swing.JLabel fondoPrincipalJLabel;
    private javax.swing.JLabel iconoCaseteJLabel;
    private javax.swing.JLabel iconoCompraJLabel;
    private javax.swing.JLabel iconoCuentaJLabel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JList<String> listaCompras;
    private javax.swing.JLabel txtCarteleraJLabel;
    private javax.swing.JTextArea txtFactura;
    // End of variables declaration//GEN-END:variables
}
