
package vista;

import java.awt.event.ActionListener;
import javax.swing.JButton;
import vista.util.ImagenEnJLabel;
import vista.util.Tema;


public class VistaAdmin extends javax.swing.JFrame {

    private ImagenEnJLabel fondo;
    private ImagenEnJLabel iconoEmpleados;
    private ImagenEnJLabel iconoPeliculas;
   
    private final int ANCHO_VENTANA = 1280; 
    private final int ALTO_VENTANA = 720;
    
    public VistaAdmin() {
        initComponents();
        configurarVentana();
        cargarImagenes();
        this.repaint();
    }
    
    public void configurarVentana() {
        this.setLocationRelativeTo(null); // Centrado
        this.setTitle("Sistema de Gestion Night Cine - Vista Administrador");
        this.setSize(ANCHO_VENTANA, ALTO_VENTANA); // Tamaño fijo 
        this.setResizable(false); // Tamaño fijo 
    }
    public void cargarImagenes() {
        fondo = new ImagenEnJLabel(fondoPrincipal, "imagenesDeFondo/fondoAdmin.png");
        iconoEmpleados = new ImagenEnJLabel(icono1, "iconos/btnAdmin1.png");
        iconoPeliculas = new ImagenEnJLabel(icono2, "iconos/btnAdmin2.png");
    }

    public void addBtnEmpleados (ActionListener l){
        btnEmpleados.addActionListener(l);
    }
    public void addBtnPeliculas(ActionListener l){
        btnPeliculas.addActionListener(l);
    }

    public void addBtnCerrarSesion (ActionListener l){
        btnCerrarSesion.addActionListener(l);
    }

    
    
    public JButton getBtnCerrarSesion() {
        return btnCerrarSesion;
    }
    
    public JButton getBtnEmpleados() {
        return btnEmpleados;
    }

    public void setBtnEmpleados(JButton btnEmpleados) {
        this.btnEmpleados = btnEmpleados;
    }



    public JButton getBtnPeliculas() {
        return btnPeliculas;
    }

    public void setBtnPeliculas(JButton btnPeliculas) {
        this.btnPeliculas = btnPeliculas;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnEmpleados = new javax.swing.JButton();
        btnPeliculas = new javax.swing.JButton();
        btnCerrarSesion = new javax.swing.JButton();
        icono2 = new javax.swing.JLabel();
        icono1 = new javax.swing.JLabel();
        fondoPrincipal = new javax.swing.JLabel();

        jButton1.setFont(new java.awt.Font("Arial Black", 1, 16)); // NOI18N
        jButton1.setText("jButton1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 517, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnEmpleados.setFont(Tema.FUENTE_BOTON);
        btnEmpleados.setForeground(Tema.CREMA_CLARO);
        btnEmpleados.setText("EMPLEADOS");
        btnEmpleados.setBorder(null);
        btnEmpleados.setBorderPainted(false);
        btnEmpleados.setContentAreaFilled(false);
        btnEmpleados.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEmpleados.setFocusPainted(false);
        btnEmpleados.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel2.add(btnEmpleados, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 270, 166, 145));

        btnPeliculas.setBackground(Tema.ROJO_VIBRANTE);
        btnPeliculas.setFont(Tema.FUENTE_BOTON);
        btnPeliculas.setForeground(Tema.CREMA_CLARO);
        btnPeliculas.setText("PELICULAS");
        btnPeliculas.setBorder(null);
        btnPeliculas.setBorderPainted(false);
        btnPeliculas.setContentAreaFilled(false);
        btnPeliculas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPeliculas.setFocusPainted(false);
        btnPeliculas.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel2.add(btnPeliculas, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 270, 166, 145));

        btnCerrarSesion.setBackground(Tema.ROJO_VIBRANTE);
        btnCerrarSesion.setFont(Tema.FUENTE_BOTON);
        btnCerrarSesion.setForeground(Tema.BLANCO);
        btnCerrarSesion.setText("Cerrar Sesion X");
        btnCerrarSesion.setBorder(null);
        btnCerrarSesion.setBorderPainted(false);
        btnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesionActionPerformed(evt);
            }
        });
        jPanel2.add(btnCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 590, 190, 50));
        jPanel2.add(icono2, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 280, 170, 170));
        jPanel2.add(icono1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 270, 170, 170));
        jPanel2.add(fondoPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCerrarSesionActionPerformed

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnEmpleados;
    private javax.swing.JButton btnPeliculas;
    private javax.swing.JLabel fondoPrincipal;
    private javax.swing.JLabel icono1;
    private javax.swing.JLabel icono2;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables

    public void cerrar() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}